# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b21d9fdf8d0187f35f6108ed1277577d751c2c779a72140b564993a6b18d2dde4e7f43f3bcabe03622f717ed7e038abb313133144743574e7569bc23752dd7

test:
  secret_key_base: 1abaac0ebd37f5ec35ccada20a38023cdf539f9871ff7789fd71dd18ff766b5b112f73c16d1047c4b1433987d59646d8933cec76db1c3b91e7c8ba1debf3c934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
